#ifndef CORE_PG_BINDINGS_TYPING_TYPES
#define CORE_PG_BINDINGS_TYPING_TYPES
#include <pqxx/pqxx>
#include <pqxx/strconv.hxx>
#include "core_types/typing/backend.hpp"
#include "core_types/typing/interface.hpp"
#include "core_pg_bindings/typing/definitions.hpp"
#include "core_pg_bindings/macros/conversions.hpp"
#include "core_pg_bindings/macros/declaration.hpp"


namespace core_pg_bindings
{
PG_CPP_DOMAIN_DECLARATION(PG_BOOLEAN);
PG_CPP_DOMAIN_DECLARATION(PG_INT1);
PG_CPP_DOMAIN_DECLARATION(PG_INT2);
PG_CPP_DOMAIN_DECLARATION(PG_INT4);
PG_CPP_DOMAIN_DECLARATION(PG_INT8);
PG_CPP_DOMAIN_DECLARATION(PG_FLOAT4);
PG_CPP_DOMAIN_DECLARATION(PG_FLOAT8);
PG_CPP_DOMAIN_DECLARATION(PG_TEXT);
PG_CPP_DOMAIN_DECLARATION(PG_TIMESTAMPTZ);
PG_CPP_DOMAIN_DECLARATION(PG_DATE);
};


namespace core_pg_bindings::interface
{
IFACE_CPP_ALIASDEF_DECLARATION(PG_BOOLEAN);
IFACE_CPP_ALIASDEF_DECLARATION(PG_INT1);
IFACE_CPP_ALIASDEF_DECLARATION(PG_INT2);
IFACE_CPP_ALIASDEF_DECLARATION(PG_INT4);
IFACE_CPP_ALIASDEF_DECLARATION(PG_INT8);
IFACE_CPP_ALIASDEF_DECLARATION(PG_FLOAT4);
IFACE_CPP_ALIASDEF_DECLARATION(PG_FLOAT8);
IFACE_CPP_ALIASDEF_DECLARATION(PG_TEXT);
IFACE_CPP_ALIASDEF_DECLARATION(PG_TIMESTAMPTZ);
IFACE_CPP_ALIASDEF_DECLARATION(PG_DATE);
};


namespace pqxx
{
// PG_DECLARE_TYPE_CONVERSION(PG_BOOLEAN, BOOST_PP_EMPTY());
// PG_DECLARE_TYPE_CONVERSION(PG_INT1, BOOST_PP_EMPTY());
// PG_DECLARE_TYPE_CONVERSION(PG_INT2, BOOST_PP_EMPTY());
// PG_DECLARE_TYPE_CONVERSION(PG_INT4, BOOST_PP_EMPTY());
// PG_DECLARE_TYPE_CONVERSION(PG_INT8, BOOST_PP_EMPTY());
// PG_DECLARE_TYPE_CONVERSION(PG_FLOAT4, BOOST_PP_EMPTY());
// PG_DECLARE_TYPE_CONVERSION(PG_FLOAT8, BOOST_PP_EMPTY());
// PG_DECLARE_TYPE_CONVERSION(PG_TEXT, BOOST_PP_EMPTY());
// YYYY-MM-DDTHH:mm:ss.UUUUUU+00:00 32 + \0
PG_DECLARE_TYPE_CONVERSION(PG_TIMESTAMPTZ, 33);
// YYYY-MM-DD 10 + \0
PG_DECLARE_TYPE_CONVERSION(PG_DATE, 11);
};


#endif
