#include "core_pg_bindings/macros/register.hpp"
#include "test_app/database/interface/types.hpp"


// NOTE TYPES
PG_TABLE_REGISTER_SUBCLASS_REG(TEST_APP_DB_AUTHOR);
PG_TABLE_REGISTER_SUBCLASS_REG(TEST_APP_DB_AUTHORED);
PG_TABLE_REGISTER_SUBCLASS_REG(TEST_APP_DB_WITH_TIMESTAMPS);
PG_ENUM_REGISTER_SUBCLASS_REG(TEST_APP_DB_POST_STATUS);
PG_TABLE_REGISTER_SUBCLASS_REG(TEST_APP_DB_POST);
PG_TABLE_REGISTER_SUBCLASS_REG(TEST_APP_DB_COMMENT);
PG_TABLE_REGISTER_SUBCLASS_REG(TEST_APP_DB_COMMENT_POST);
PG_TABLE_REGISTER_SUBCLASS_REG(TEST_APP_DB_COMPOSITE_AUTHOR);


