#ifndef CORE_PG_BINDINGS_MACROS_DEFINITION
#define CORE_PG_BINDINGS_MACROS_DEFINITION
#include "core_types/macros/definition.hpp"


// NOTE DEFINITIONS
#define PG_COMPOSED_TABLE_DEFINITION COMPOSED_DATACLASS_DEFINITION
#define PG_TABLE_DEFINITION          DATACLASS_DEFINITION
#define PG_COLUMN                    DATACLASS_MEMBER

#define PG_COMPOSITE_DEFINITION      DATACLASS_DEFINITION
#define PG_ATTRIBUTE                 DATACLASS_MEMBER

#define PG_ENUM_DEFINITION           ENUM_DEFINITION
#define PG_ENUM_VALUE                ENUM_MEMBER


// NOTE ALIAS
#define PG_TYPE_DOMAIN               TYPE_DEFINITION_ALIAS
#define PG_ENUM_DOMAIN               ENUM_DEFINITION_ALIAS
#define PG_COMPOSITE_DOMAIN          DATACLASS_DEFINITION_ALIAS


// NOTE FUNCTIONS
#define PG_OL_DEFINITION()\
    BOOST_PP_TUPLE_ELEM(0, OVERLOAD_DEF)


#define PG_OVERLOAD(DEFINITION)(\
    DEFINITION\
)

#define PG_INVOKABLE(NAME, CLS)(\
    NAME,\
    CLS,\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY()\
)

#endif
