#ifndef CORE_PG_BINDINGS_MACROS_REGISTER
#define CORE_PG_BINDINGS_MACROS_REGISTER
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "core_types/macros/register/descriptive.hpp"
#include "core_types/macros/register/instanceable.hpp"


// NOTE REGISTER MAIN TYPES IN MODULE
#define PG_TABLE_REGISTER                        CT_CLASSDEF_REGISTER_INSTANCEABLE
#define PG_COMPOSITE_REGISTER                    CT_CLASSDEF_REGISTER_INSTANCEABLE
#define PG_TYPE_REGISTER                         CT_TYPEDEF_REGISTER_INSTANCEABLE
#define PG_ENUM_REGISTER                         CT_ENUMDEF_REGISTER_INSTANCEABLE

#define PG_TABLE_REGISTER_DESCRIPTIVE            CT_CLASSDEF_REGISTER_DESCRIPTIVE
#define PG_COMPOSITE_REGISTER_DESCRIPTIVE        CT_CLASSDEF_REGISTER_DESCRIPTIVE
#define PG_TYPE_REGISTER_DESCRIPTIVE             CT_TYPEDEF_REGISTER_DESCRIPTIVE
#define PG_ENUM_REGISTER_DESCRIPTIVE             CT_ENUMDEF_REGISTER_DESCRIPTIVE


// NOTE REGISTER DOMAIN TYPES IN MODULE
#define PG_COMPOSITE_DOMAIN_REGISTER             CT_CLASS_ALIASDEF_REGISTER_INSTANCEABLE
#define PG_TYPE_DOMAIN_REGISTER                  CT_TYPE_ALIASDEF_REGISTER_INSTANCEABLE
#define PG_ENUM_DOMAIN_REGISTER                  CT_ENUM_ALIASDEF_REGISTER_INSTANCEABLE

#define PG_COMPOSITE_DOMAIN_REGISTER_DESCRIPTIVE CT_CLASS_ALIASDEF_REGISTER_DESCRIPTIVE
#define PG_TYPE_DOMAIN_REGISTER_DESCRIPTIVE      CT_TYPE_ALIASDEF_REGISTER_DESCRIPTIVE
#define PG_ENUM_DOMAIN_REGISTER_DESCRIPTIVE      CT_ENUM_ALIASDEF_REGISTER_DESCRIPTIVE


// NOTE SUBCLASS REGISTRY
#define PG_TYPE_REGISTER_SUBCLASS_REG            CT_TYPEDEF_REGISTER_SUBCLASS_REG
#define PG_DOMAIN_REGISTER_SUBCLASS_REG          CT_ALIASDEF_REGISTER_SUBCLASS_REG
#define PG_ENUM_REGISTER_SUBCLASS_REG            CT_ENUMDEF_REGISTER_SUBCLASS_REG
#define PG_TABLE_REGISTER_SUBCLASS_REG           CT_CLASSDEF_REGISTER_SUBCLASS_REG


#define PG_INVOKABLE_REGISTER(FUNC_DEF, m)\
pybind11::class_<T_QUALNAME(T_NAMETUPLE(FUNC_DEF))>(m, BOOST_PP_STRINGIZE(T_NAME(T_NAMETUPLE(FUNC_DEF))))\
.def_property_readonly_static("_cpp_overloads", [](const py::object&) -> std::vector<std::string_view> {\
    return T_QUALNAME(T_NAMETUPLE(FUNC_DEF))::overloads;\
})


#endif
