#ifndef TEST_APP_DATABASE_INTERFACE_TYPES
#define TEST_APP_DATABASE_INTERFACE_TYPES
#include "test_app/database/typing/definitions.hpp"
#include "test_app/database/typing/namespace.hpp"


namespace test_app::database::interface
{
// NOTE TYPES
    // TEST_APP_DB_AUTHORED
IFACE_CPP_CLASSDEF_DECLARATION(TEST_APP_DB_AUTHORED);
IFACE_CPP_CLASSDEF_DECLARATION(TEST_APP_DB_WITH_TIMESTAMPS);
IFACE_CPP_CLASSDEF_DECLARATION(TEST_APP_DB_AUTHOR);
IFACE_CPP_ENUMDEF_DECLARATION(TEST_APP_DB_POST_STATUS);
IFACE_CPP_CLASSDEF_DECLARATION(TEST_APP_DB_POST);
IFACE_CPP_CLASSDEF_DECLARATION(TEST_APP_DB_COMMENT);
IFACE_CPP_CLASSDEF_DECLARATION(TEST_APP_DB_COMMENT_POST);
IFACE_CPP_CLASSDEF_DECLARATION(TEST_APP_DB_COMPOSITE_AUTHOR);
IFACE_CPP_ALIASDEF_DECLARATION(TEST_APP_DB_DOMAIN);
};


namespace pqxx
{
PG_DECLARE_TABLE_CONVERSION(TEST_APP_DB_AUTHOR);
PG_DECLARE_TABLE_CONVERSION(TEST_APP_DB_AUTHORED);
PG_DECLARE_TABLE_CONVERSION(TEST_APP_DB_WITH_TIMESTAMPS);
PG_DECLARE_ENUM_CONVERSION(TEST_APP_DB_POST_STATUS);
PG_DECLARE_TABLE_CONVERSION(TEST_APP_DB_POST);
PG_DECLARE_TABLE_CONVERSION(TEST_APP_DB_COMMENT);
PG_DECLARE_COMPOSITE_CONVERSION(TEST_APP_DB_COMMENT_POST);
PG_DECLARE_COMPOSITE_CONVERSION(TEST_APP_DB_COMPOSITE_AUTHOR);
};

#endif
