#ifndef PG_DEFINITION_INCLUDE_TYPES
#define PG_DEFINITION_INCLUDE_TYPES


#include <pqxx/pqxx>
#include <pqxx/strconv.hxx>

#include "base_types/compare.hpp"
#include "base_types/types.hpp"

#include "pg_definition/macros/definition.hpp"
#include "pg_definition/macros/conversions.hpp"


namespace pg_definition
{
    PG_CPP_DOMAIN_DECLARATION(PG_BOOLEAN);
    PG_CPP_DOMAIN_DECLARATION(PG_INT1);
    PG_CPP_DOMAIN_DECLARATION(PG_INT2);
    PG_CPP_DOMAIN_DECLARATION(PG_INT4);
    PG_CPP_DOMAIN_DECLARATION(PG_INT8);
    PG_CPP_DOMAIN_DECLARATION(PG_FLOAT4);
    PG_CPP_DOMAIN_DECLARATION(PG_FLOAT8);
    PG_CPP_DOMAIN_DECLARATION(PG_TEXT);
    PG_CPP_DOMAIN_DECLARATION(PG_TIMESTAMPTZ);
    PG_CPP_DOMAIN_DECLARATION(PG_DATE);
};


namespace pqxx
{

    PG_TYPEDEF_CONVERSION(PG_BOOLEAN, BOOST_PP_EMPTY());
    PG_TYPEDEF_CONVERSION(PG_INT1, BOOST_PP_EMPTY());
    PG_TYPEDEF_CONVERSION(PG_INT2, BOOST_PP_EMPTY());
    PG_TYPEDEF_CONVERSION(PG_INT4, BOOST_PP_EMPTY());
    PG_TYPEDEF_CONVERSION(PG_INT8, BOOST_PP_EMPTY());
    PG_TYPEDEF_CONVERSION(PG_FLOAT4, BOOST_PP_EMPTY());
    PG_TYPEDEF_CONVERSION(PG_FLOAT8, BOOST_PP_EMPTY());
    PG_TYPEDEF_CONVERSION(PG_TEXT, BOOST_PP_EMPTY());
    // YYYY-MM-DDTHH:mm:ss.UUUUUU+00:00 32 + \0
    PG_TYPEDEF_CONVERSION(PG_TIMESTAMPTZ, 33);
    // YYYY-MM-DD 10 + \0
    PG_TYPEDEF_CONVERSION(PG_DATE, 11);
};


#endif
