#ifndef CORE_PG_BINDINGS_MACROS_DEFINITIONS
#define CORE_PG_BINDINGS_MACROS_DEFINITIONS
#include "core_types/macros/definition.hpp"


// NOTE DEFINITIONS
#define PG_TABLE_NO_BASES_DEFINITION NO_BASES_DATACLASS_DEFINITION
#define PG_TABLE_DEFINITION DATACLASS_DEFINITION
#define PG_COLUMN DATACLASS_MEMBER
#define PG_OPTIONAL_COLUMN OPTIONAL_DATACLASS_MEMBER

#define PG_COMPOSITE_DEFINITION NO_BASES_DATACLASS_DEFINITION
#define PG_ATTRIBUTE DATACLASS_MEMBER

#define PG_ENUM_DEFINITION ENUM_DEFINITION
#define PG_ENUM_VALUE ENUM_MEMBER


// NOTE DECLARATIONS
#define PG_CPP_TABLE_DECLARATION CPP_CLASSDEF_DECLARATION
#define PG_CPP_ENUM_DECLARATION CPP_ENUMDEF_DECLARATION
#define PG_CPP_DOMAIN_DECLARATION CPP_ALIASDEF_DECLARATION


// NOTE ALIAS
#define PG_TYPEDEF_DOMAIN TYPE_DEFINITION_ALIAS
#define PG_ENUMDEF_DOMAIN ENUM_DEFINITION_ALIAS
#define PG_CLASSDEF_DOMAIN DATACLASS_DEFINITION_ALIAS

// NOTE CONSTANTS
/*
#define EXPOSE_EXTERN_TRANSACTION 0
#define EXPOSE_AUTO_TRANSACTION 1
#define EXPOSE_EXTERN_AUTO_TRANSACTION 2
#define REQUIRED 1
#define OPTIONAL 0
#define IS_PROCEDURE 1
#define IS_FUNCTION 0


// NOTE FUNCTION DEFINITION METHODS
#define F_MACRO_NAME(FUNC_DEF)\
BOOST_PP_TUPLE_ELEM(0, FUNC_DEF)


#define F_NAMETUPLE(FUNC_DEF)\
BOOST_PP_TUPLE_ELEM(1, FUNC_DEF)


#define F_OVERLOADS(FUNC_DEF)\
BOOST_PP_TUPLE_ELEM(2, FUNC_DEF)


#define F_IS_PROCEDURE(FUNC_DEF)\
BOOST_PP_TUPLE_ELEM(3, FUNC_DEF)


#define F_MAIN_OVERLOAD(FUNC_DEF)\
BOOST_PP_SEQ_HEAD(F_OVERLOADS(FUNC_DEF))


// NOTE FUNCTION OVERLOAD METHODS
#define F_OL_ALIAS(OVERLOAD_DEF)\
BOOST_PP_TUPLE_ELEM(0, OVERLOAD_DEF)


#define F_OL_RETURN_TYPE(OVERLOAD_DEF)\
BOOST_PP_TUPLE_ELEM(1, OVERLOAD_DEF)


#define F_OL_EXPOSURE_TYPE(OVERLOAD_DEF)\
BOOST_PP_TUPLE_ELEM(2, OVERLOAD_DEF)


#define F_OL_PARAMETERS(OVERLOAD_DEF)\
BOOST_PP_TUPLE_ELEM(3, OVERLOAD_DEF)


// NOTE FUNCTION OVERLOAD METHODS
#define F_OL_P_TYPE(PARAM_DEF)\
BOOST_PP_TUPLE_ELEM(0, PARAM_DEF)


#define F_OL_P_NAME(PARAM_DEF)\
BOOST_PP_TUPLE_ELEM(1, PARAM_DEF)


// NOTE FUNCTION DEFINITION
#define OL_PARAMETER(BASE_TP, NAME)(\
    BASE_TP,\
    NAME\
)


#define FUNCTION_OVERLOAD(ALIAS, RETURN_TYPE, EXPOSURE_TYPE, PARAMETERS)(\
    ALIAS,\
    RETURN_TYPE,\
    EXPOSURE_TYPE,\
    PARAMETERS\
)


#define EMPTY_FUNCTION_OVERLOAD(ALIAS, RETURN_TYPE, EXPOSURE_TYPE)(\
    ALIAS,\
    RETURN_TYPE,\
    EXPOSURE_TYPE,\
    BOOST_PP_EMPTY()\
)


#define PG_FUNCTION(NAME, CLS, OVERLOADS)(\
    NAME,\
    CLS,\
    OVERLOADS,\
    0\
)


#define PG_PROCEDURE(NAME, CLS, OVERLOADS)(\
    NAME,\
    CLS,\
    OVERLOADS,\
    1\
)


#define NO_RESULT_TYPE TYPE_DEFINITION(\
    NO_RESULT_TYPE,\
    (std, optional<bool>),\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY()\
)
#ifndef CORE_PG_BINDINGS_MACROS_FUNCTIONS
#define CORE_PG_BINDINGS_MACROS_FUNCTIONS
#include "core_pg_bindings/macros/definition.hpp"


namespace pg = core_pg_bindings;


#define F_CPP_ENUMERATE_PARAM_TYPES(r, data, i, elem)\
    BOOST_PP_COMMA_IF(i) const FOP_TYPE(T_QUALNAME(T_NAMETUPLE(elem)))&


#define F_CPP_OVERLOAD_DECLARATION(OVERLOAD_DEF, WITH_TX)\
BOOST_PP_IF(\
    T_IS_OPTIONAL(F_OL_RETURN_TYPE(OVERLOAD_DEF)),\
    std::optional<ResultType>,\
    ResultType\
) overload() (\
BOOST_PP_IF(WITH_TX, pqxx::work&, BOOST_PP_EMPTY())\
BOOST_PP_COMMA_IF(WITH_TX)\
BOOST_PP_SEQ_FOR_EACH_I(F_ENUMERATE_PARAM_TYPES, BOOST_PP_EMPTY(), F_OL_PARAMETERS(OVERLOAD_DEF)));


#define F_CPP_EXPOSE_OVERLOAD(r, data, elem)\
BOOST_PP_IF(\
BOOST_PP_EQ(F_OL_EXPOSURE_TYPE(elem), 0),\
F_CPP_OVERLOAD_DECLARATION(elem, 0),\
BOOST_PP_IF(\
    BOOST_PP_EQ(F_OL_EXPOSURE_TYPE(elem), 1),\
        F_CPP_OVERLOAD_DECLARATION(elem, 1),\
        F_CPP_OVERLOAD_DECLARATION(elem, 0); F_CPP_OVERLOAD_DECLARATION(elem, 1)\
    )\
);


#define PG_FETCH_ONE_FUNCTION(FUNC_DEF)\
class T_NAME(T_NAMETUPLE(FUNC_DEF))\
: public pg::queries_database_on_transaction<\
        pg::fetch_one_functor,\
        BOOST_PP_IF(\
            T_IS_OPTIONAL(F_OL_RETURN_TYPE(F_MAIN_OVERLOAD(FUNC_DEF))),\
            pg::OptionalResult_<pg::SingleResult_<T_QUALNAME(T_NAMETUPLE(F_OL_RETURN_TYPE(F_MAIN_OVERLOAD(FUNC_DEF))))>>,\
            pg::SingleResult_<T_QUALNAME(T_NAMETUPLE(F_OL_RETURN_TYPE(F_MAIN_OVERLOAD(FUNC_DEF))))>\
        ),\
        BOOST_PP_SEQ_FOR_EACH_I(F_CPP_ENUMERATE_PARAM_TYPES, BOOST_PP_EMPTY(), F_MAIN_OVERLOAD(FUNC_DEF))>\
{\
protected:\
    std::shared_ptr<pg::query_configuration> query_config () const override;\
public:\
    static pg::overload_registry overload_reg;\
    BOOST_PP_SEQ_FOR_EACH(F_CPP_EXPOSE_OVERLOAD, FUNC_DEF, F_OVERLOADS(FUNC_DEF))\
}


#define PG_FETCH_MANY_FUNCTION(FUNC_DEF)\
class T_NAME(T_NAMETUPLE(FUNC_DEF))\
: public pg::queries_database_on_transaction<\
        pg::fetch_many_functor,\
        BOOST_PP_IF(\
            T_IS_OPTIONAL(F_OL_RETURN_TYPE(F_MAIN_OVERLOAD(FUNC_DEF))),\
            pg::OptionalResult_<pg::ContainedResult_<T_QUALNAME(T_NAMETUPLE(F_OL_RETURN_TYPE(F_MAIN_OVERLOAD(FUNC_DEF))))>>,\
            pg::ContainedResult_<T_QUALNAME(T_NAMETUPLE(F_OL_RETURN_TYPE(F_MAIN_OVERLOAD(FUNC_DEF))))>\
        ),\
        BOOST_PP_SEQ_FOR_EACH_I(F_CPP_ENUMERATE_PARAM_TYPES, BOOST_PP_EMPTY(), BOOST_PP_TUPLE_ELEM(0, F_MAIN_OVERLOAD(FUNC_DEF)))>\
{\
protected:\
    std::shared_ptr<pg::query_configuration> query_config () const override;\
public:\
    static pg::overload_registry overload_reg;\
    BOOST_PP_SEQ_FOR_EACH(F_CPP_EXPOSE_OVERLOAD, FUNC_DEF, F_OVERLOADS(FUNC_DEF))\
}


#define PG_FETCH_NONE_FUNCTION(FUNC_DEF)\
class T_NAME(T_NAMETUPLE(FUNC_DEF))\
: public pg::queries_database_on_transaction<\
        pg::fetch_none_functor,\
        pg::NoResult_,\
        BOOST_PP_SEQ_FOR_EACH_I(F_CPP_ENUMERATE_PARAM_TYPES, BOOST_PP_EMPTY(), BOOST_PP_TUPLE_ELEM(0, F_MAIN_OVERLOAD(FUNC_DEF)))>\
{\
protected:\
    std::shared_ptr<pg::query_configuration> query_config () const override;\
public:\
    static pg::overload_registry overload_reg;\
    BOOST_PP_SEQ_FOR_EACH(F_CPP_EXPOSE_OVERLOAD, FUNC_DEF, F_OVERLOADS(FUNC_DEF))\
}


#define F_CPP_EXPAND_OVERLOAD_PARAMS_FOR_QUERY(r, data, i, elem)\
BOOST_PP_COMMA_IF(i) FD_PARAM_NAME(elem) := BOOST_PP_CAT($, i)



#define PG_INITIALIZE_FUNCTION_CALL(FUNC_DEF)\
pg::overload_registry T_QUALNAME(T_NAMETUPLE(FUNC_DEF))::overload_reg = pg::overload_registry();\
std::shared_ptr<pg::query_configuration> T_QUALNAME(T_NAMETUPLE(FUNC_DEF))::query_config () const\
{\
    return std::make_shared<pg::query_configuration>(\
        BOOST_PP_IF(\
            PG_IS_PROCEDURE(FUNC_DEF),\
            BOOST_PP_STRINGIZE(CALL T_NAME(T_NAMETUPLE(FUNC_DEF))(BOOST_PP_SEQ_FOR_EACH_I(PG_EXPAND_OVERLOAD_PARAMS_FOR_QUERY, FUNC_DEF, BOOST_PP_TUPLE_ELEM(0, FD_OVERLOADS(FUNC_DEF))))),\
            BOOST_PP_STRINGIZE(SELECT T_NAME(T_NAMETUPLE(FUNC_DEF))(BOOST_PP_SEQ_FOR_EACH_I(PG_EXPAND_OVERLOAD_PARAMS_FOR_QUERY, FUNC_DEF, BOOST_PP_TUPLE_ELEM(0, FD_OVERLOADS(FUNC_DEF)))))\
        )\
        T_NAMESPACE(T_NAMETUPLE(FUNC_DEF))::database_env::env()\
    );\
}


#define PG_INITIALIZE_FUNCTION_QUERY(FUNC_DEF, QUERY)\
pg::overload_registry T_QUALNAME(T_NAMETUPLE(FUNC_DEF))::overload_reg = pg::overload_registry();\
std::shared_ptr<pg::query_configuration> T_QUALNAME(T_NAMETUPLE(FUNC_DEF))::query_config () const\
{\
    return std::make_shared<pg::query_configuration>(\
        QUERY,\
        T_NAMESPACE(T_NAMETUPLE(FUNC_DEF))::database_env::env()\
    );\
}


#define OVERLOAD_MEMBERS_FOR_REG(r, data, i, elem)\
BOOST_PP_COMMA_IF(i) {BOOST_PP_STRINGIZE(FD_PARAM_NAME(elem)), FD_PARAM_QUALIFIED_TYPE(elem)}


#define PG_REGISTER_FUNCTION_OVERLOAD(r, data, elem)\
T_QUALNAME(T_NAMETUPLE(data))::overload_reg.register_map(\
    BOOST_PP_STRINGIZE(FD_OL_ALIAS(elem)),\
    std::make_unique<std::map<std::string, py::object>>(BOOST_PP_SEQ_FOR_EACH_I(OVERLOAD_REG_MEMBERS, BOOST_PP_EMPTY(), FD_OL_PARAMS(elem))\
);


#define PG_REGISTER_FUNCTION_OVERLOADS(FUNC_DEF)\
BOOST_PP_SEQ_FOR_EACH(PG_REGISTER_FUNCTION_OVERLOAD, FUNC_DEF, FD_OVERLOADS(FUNC_DEF))


#endif*/


#endif
