#ifndef CORE_PG_BINDINGS_MACROS_DEFINITIONS
#define CORE_PG_BINDINGS_MACROS_DEFINITIONS
#include "core_types/macros/definition.hpp"


// DEFINITIONS
#define PG_TABLE_NO_BASES_DEFINITION NO_BASES_DATACLASS_DEFINITION
#define PG_TABLE_DEFINITION DATACLASS_DEFINITION
#define PG_COLUMN DATACLASS_MEMBER
#define PG_OPTIONAL_COLUMN OPTIONAL_DATACLASS_MEMBER


#define PG_COMPOSITE_DEFINITION NO_BASES_DATACLASS_DEFINITION
#define PG_ATTRIBUTE DATACLASS_MEMBER


#define PG_ENUM_DEFINITION ENUM_DEFINITION
#define PG_ENUM_VALUE ENUM_MEMBER


// DECLARATIONS
#define PG_CPP_TABLE_DECLARATION CPP_CLASSDEF_DECLARATION
#define PG_CPP_ENUM_DECLARATION CPP_ENUMDEF_DECLARATION
#define PG_CPP_DOMAIN_DECLARATION CPP_ALIASDEF_DECLARATION


// ALIAS 
#define PG_TYPEDEF_DOMAIN TYPE_DEFINITION_ALIAS
#define PG_ENUMDEF_DOMAIN ENUM_DEFINITION_ALIAS
#define PG_CLASSDEF_DOMAIN DATACLASS_DEFINITION_ALIAS


#endif
