#ifndef CORE_PG_BINDINGS_MACROS_DEFINITIONS
#define CORE_PG_BINDINGS_MACROS_DEFINITIONS


#include "core_types/macros/definition.hpp"


// DEFINITIONS
#define PG_TABLE_NO_BASES_DEFINITION NO_BASES_DATACLASS_DEFINITION
#define PG_TABLE_DEFINITION DATACLASS_DEFINITION
#define PG_COLUMN DATACLASS_MEMBER
#define PG_OPTIONAL_COLUMN OPTIONAL_DATACLASS_MEMBER


#define PG_COMPOSITE_DEFINITION NO_BASES_DATACLASS_DEFINITION
#define PG_ATTRIBUTE DATACLASS_MEMBER


#define PG_ENUM_DEFINITION ENUM_DEFINITION
#define PG_ENUM_VALUE ENUM_MEMBER


// DECLARATIONS
#define PG_CPP_TABLE_DECLARATION CPP_CLASSDEF_DECLARATION
#define PG_CPP_ENUM_DECLARATION CPP_ENUMDEF_DECLARATION
#define PG_CPP_DOMAIN_DECLARATION CPP_ALIASDEF_DECLARATION


// ALIAS 
#define PG_TYPEDEF_DOMAIN TYPE_DEFINITION_ALIAS
#define PG_ENUMDEF_DOMAIN ENUM_DEFINITION_ALIAS
#define PG_CLASSDEF_DOMAIN DATACLASS_DEFINITION_ALIAS


#define PG_BOOLEAN PG_TYPEDEF_DOMAIN(\
    PG_BOOLEAN,\
    (core_pg_bindings, boolean),\
    BTP_BOOLEAN\
)
#define PG_BOOLEAN_CONSTRUCTORS (PG_BOOLEAN) BTP_BOOLEAN_CONSTRUCTORS
#define PG_BOOLEAN_INHERITANCE_CHAIN (BTP_BOOLEAN)


// TYPE ALIAS
#define PG_INT1 PG_TYPEDEF_DOMAIN(\
    PG_INT1,\
    (core_pg_bindings, int1),\
    BTP_INT1\
)
#define PG_INT1_CONSTRUCTORS (PG_INT1) BTP_INT1_CONSTRUCTORS
#define PG_INT1_INHERITANCE_CHAIN (BTP_INT1)


#define PG_INT2 PG_TYPEDEF_DOMAIN(\
    PG_INT2,\
    (core_pg_bindings, int2),\
    BTP_INT2\
)
#define PG_INT2_CONSTRUCTORS (PG_INT2) BTP_INT2_CONSTRUCTORS
#define PG_INT2_INHERITANCE_CHAIN (BTP_INT2)


#define PG_INT4 PG_TYPEDEF_DOMAIN(\
    PG_INT4,\
    (core_pg_bindings, int4),\
    BTP_INT4\
)
#define PG_INT4_CONSTRUCTORS (PG_INT4) BTP_INT4_CONSTRUCTORS
#define PG_INT4_INHERITANCE_CHAIN (BTP_INT4)


#define PG_INT8 PG_TYPEDEF_DOMAIN(\
    PG_INT8,\
    (core_pg_bindings, int8),\
    BTP_INT8\
)
#define PG_INT8_CONSTRUCTORS (PG_INT8) BTP_INT8_CONSTRUCTORS
#define PG_INT8_INHERITANCE_CHAIN (BTP_INT8)


#define PG_FLOAT4 PG_TYPEDEF_DOMAIN(\
    PG_FLOAT4,\
    (core_pg_bindings, float4),\
    BTP_FLOAT4\
)
#define PG_FLOAT4_CONSTRUCTORS (PG_FLOAT4) BTP_FLOAT4_CONSTRUCTORS
#define PG_FLOAT4_INHERITANCE_CHAIN (BTP_FLOAT4)


#define PG_FLOAT8 PG_TYPEDEF_DOMAIN(\
    PG_FLOAT8,\
    (core_pg_bindings, float8),\
    BTP_FLOAT8\
)
#define PG_FLOAT8_CONSTRUCTORS (PG_FLOAT8) BTP_FLOAT8_CONSTRUCTORS
#define PG_FLOAT8_INHERITANCE_CHAIN (BTP_FLOAT8)


#define PG_TEXT PG_TYPEDEF_DOMAIN(\
    PG_TEXT,\
    (core_pg_bindings, text),\
    BTP_TEXT\
)
#define PG_TEXT_CONSTRUCTORS (PG_TEXT) BTP_TEXT_CONSTRUCTORS
#define PG_TEXT_INHERITANCE_CHAIN (BTP_TEXT)


#define PG_TIMESTAMPTZ PG_TYPEDEF_DOMAIN(\
    PG_TIMESTAMPTZ,\
    (core_pg_bindings, timestamptz),\
    BTP_TIMESTAMPTZ\
)
#define PG_TIMESTAMPTZ_CONSTRUCTORS (PG_TIMESTAMPTZ) BTP_TIMESTAMPTZ_CONSTRUCTORS
#define PG_TIMESTAMPTZ_INHERITANCE_CHAIN (BTP_TIMESTAMPTZ)


#define PG_DATE PG_TYPEDEF_DOMAIN(\
    PG_DATE,\
    (core_pg_bindings, date),\
    BTP_DATE\
)
#define PG_DATE_CONSTRUCTORS (PG_DATE) BTP_DATE_CONSTRUCTORS
#define PG_DATE_INHERITANCE_CHAIN (BTP_DATE)


#endif
