#ifndef TEST_APP_DATABASE_TYPING_NAMESPACE
#define TEST_APP_DATABASE_TYPING_NAMESPACE
#include "core_pg_bindings/macros/declaration.hpp"
#include "core_pg_bindings/typing/definitions.hpp"
#include "core_pg_bindings/typing/types.hpp"
#include "test_app/database/typing/definitions.hpp"


namespace pg = core_pg_bindings;


namespace test_app
{

};


namespace test_app::database
{
// NOTE TYPES
PG_CPP_TABLE_DECLARATION(TEST_APP_DB_AUTHORED);
PG_CPP_TABLE_DECLARATION(TEST_APP_DB_WITH_TIMESTAMPS);
PG_CPP_TABLE_DECLARATION(TEST_APP_DB_AUTHOR);
PG_CPP_ENUM_DECLARATION(TEST_APP_DB_POST_STATUS);
PG_CPP_TABLE_DECLARATION(TEST_APP_DB_POST);
PG_CPP_TABLE_DECLARATION(TEST_APP_DB_COMMENT);
PG_CPP_TABLE_DECLARATION(TEST_APP_DB_COMMENT_POST);
PG_CPP_TABLE_DECLARATION(TEST_APP_DB_COMPOSITE_AUTHOR);
PG_CPP_DOMAIN_DECLARATION(TEST_APP_DB_DOMAIN);
// NOTE FUNCTIONS
PG_CPP_INVOKABLE_DECLARATION(TEST_APP_DB_GET_AUTHOR_POSTS);
PG_CPP_INVOKABLE_DECLARATION(TEST_APP_DB_CREATE_POST);
PG_CPP_INVOKABLE_DECLARATION(TEST_APP_DB_CREATE_COMMENT);
PG_CPP_INVOKABLE_DECLARATION(TEST_APP_DB_GET_POST_COMMENTS);
PG_CPP_INVOKABLE_DECLARATION(TEST_APP_DB_AS_COMMENT_POST);
PG_CPP_INVOKABLE_DECLARATION(TEST_APP_DB_CREATE_AUTHOR);
};


#endif // TEST_APP_TYPES
