#ifndef TEST_APP_DATABASE_TYPES
#define TEST_APP_DATABASE_TYPES
#include "core_pg_bindings/typing/definitions.hpp"
#include "core_pg_bindings/typing/types.hpp"
#include "test_app/database/definitions.hpp"


namespace pg = core_pg_bindings;


namespace test_app
{
PG_CPP_TABLE_DECLARATION(TEST_APP_AUTHOR);
PG_CPP_TABLE_DECLARATION(TEST_APP_AUTHORED);
PG_CPP_TABLE_DECLARATION(TEST_APP_WITH_TIMESTAMPS);
PG_CPP_ENUM_DECLARATION(TEST_APP_POST_STATUS);
PG_CPP_TABLE_DECLARATION(TEST_APP_POST);
PG_CPP_TABLE_DECLARATION(TEST_APP_COMMENT);
PG_CPP_TABLE_DECLARATION(TEST_APP_COMMENT_POST);
PG_CPP_TABLE_DECLARATION(TEST_APP_COMPOSITE_AUTHOR);
};


namespace pqxx 
{
PG_DECLARE_TABLE_CONVERSION(TEST_APP_AUTHOR);
PG_DECLARE_TABLE_CONVERSION(TEST_APP_AUTHORED);
PG_DECLARE_TABLE_CONVERSION(TEST_APP_WITH_TIMESTAMPS);
PG_DECLARE_ENUM_CONVERSION(TEST_APP_POST_STATUS);
PG_DECLARE_TABLE_CONVERSION(TEST_APP_POST);
PG_DECLARE_TABLE_CONVERSION(TEST_APP_COMMENT);
PG_DECLARE_COMPOSITE_CONVERSION(TEST_APP_COMMENT_POST);
PG_DECLARE_COMPOSITE_CONVERSION(TEST_APP_COMPOSITE_AUTHOR);
};


#endif // TEST_APP_TYPES
