#ifndef CORE_PG_BINDINGS_MACROS_DEFINITION
#define CORE_PG_BINDINGS_MACROS_DEFINITION
#include "core_types/macros/definition.hpp"


// NOTE DEFINITIONS
#define PG_TABLE_DEFINITION            DATACLASS_DEFINITION
#define PG_COLUMN                      DATACLASS_MEMBER

#define PG_COMPOSITE_DEFINITION(NAME, CLS, MEMBERS, IFACE_CLS)\
DATACLASS_DEFINITION(NAME, CLS, MEMBERS, NONE, IFACE_CLS)
#define PG_ATTRIBUTE                   DATACLASS_MEMBER

#define PG_ENUM_DEFINITION             ENUM_DEFINITION
#define PG_ENUM_VALUE                  ENUM_MEMBER


// NOTE ALIAS
#define PG_TYPE_DOMAIN_DEFINITION      TYPE_DEFINITION_ALIAS
#define PG_ENUM_DOMAIN_DEFINITION      ENUM_DEFINITION_ALIAS
#define PG_COMPOSITE_DOMAIN_DEFINITION DATACLASS_DEFINITION_ALIAS


// NOTE FUNCTIONS
#define PG_INVOKABLE(NAME, CLS)(\
    NAME,\
    CLS,\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY(),\
    CT_FUNCDEF_IDENTIFIER,\
    CLS\
)

#endif
