#include "core_pg_bindings/types.hpp"
#include "core_pg_bindings/macros/register.hpp"


PG_PY_DOMAIN_DECLARE_SUBCLASS_REG(PG_BOOLEAN);
PG_PY_DOMAIN_DECLARE_SUBCLASS_REG(PG_INT1);
PG_PY_DOMAIN_DECLARE_SUBCLASS_REG(PG_INT2);
PG_PY_DOMAIN_DECLARE_SUBCLASS_REG(PG_INT4);
PG_PY_DOMAIN_DECLARE_SUBCLASS_REG(PG_INT8);
PG_PY_DOMAIN_DECLARE_SUBCLASS_REG(PG_FLOAT4);
PG_PY_DOMAIN_DECLARE_SUBCLASS_REG(PG_FLOAT8);
PG_PY_DOMAIN_DECLARE_SUBCLASS_REG(PG_TEXT);
PG_PY_DOMAIN_DECLARE_SUBCLASS_REG(PG_TIMESTAMPTZ);
PG_PY_DOMAIN_DECLARE_SUBCLASS_REG(PG_DATE);
