#ifndef TEST_APP_DESCRIPTION_DEFINITION
#define TEST_APP_DESCRIPTION_DEFINITION
#include "core_pg_bindings/macros/definition.hpp"


#define TEST_APP_AUTHOR PG_TABLE_NO_BASES_DEFINITION(\
    TEST_APP_AUTHOR,\
    (test_app, author),\
    (PG_COLUMN(PG_INT8, id))\
    (PG_COLUMN(PG_TEXT, name))\
)
#define TEST_APP_AUTHOR_MEMBERS T_DIRECT_MEMBERS(TEST_APP_AUTHOR)
#define TEST_APP_AUTHOR_CONSTRUCTORS (TEST_APP_AUTHOR)


#define TEST_APP_AUTHORED PG_TABLE_NO_BASES_DEFINITION(\
    TEST_APP_AUTHORED,\
    (test_app, authored),\
    (PG_COLUMN(PG_INT8, author_id))\
    (PG_COLUMN(PG_TEXT, content))\
)
#define TEST_APP_AUTHORED_MEMBERS T_DIRECT_MEMBERS(TEST_APP_AUTHORED)
#define TEST_APP_AUTHORED_CONSTRUCTORS (TEST_APP_AUTHORED)


#define TEST_APP_WITH_TIMESTAMPS PG_TABLE_NO_BASES_DEFINITION(\
    TEST_APP_WITH_TIMESTAMPS,\
    (test_app, with_timestamps),\
    (PG_COLUMN(PG_TIMESTAMPTZ, created_at))\
    (PG_COLUMN(PG_TIMESTAMPTZ, updated_at))\
)
#define TEST_APP_WITH_TIMESTAMPS_MEMBERS T_DIRECT_MEMBERS(TEST_APP_WITH_TIMESTAMPS)
#define TEST_APP_WITH_TIMESTAMPS_CONSTRUCTORS (TEST_APP_WITH_TIMESTAMPS)


#define TEST_APP_POST_STATUS PG_ENUM_DEFINITION(\
    TEST_APP_POST_STATUS,\
    (test_app, post_status),\
    (PG_ENUM_VALUE(published))\
    (PG_ENUM_VALUE(waiting_approval))\
    (PG_ENUM_VALUE(draft))\
)
#define TEST_APP_POST_STATUS_CONSTRUCTORS (TEST_APP_POST_STATUS)


#define TEST_APP_POST PG_TABLE_DEFINITION(\
    TEST_APP_POST,\
    (test_app, post),\
    (PG_COLUMN(PG_INT8, id))\
    (PG_COLUMN(PG_TEXT, title))\
    (PG_COLUMN(TEST_APP_POST_STATUS, status)),\
    (TEST_APP_AUTHORED)(TEST_APP_WITH_TIMESTAMPS)\
)
#define TEST_APP_POST_MEMBERS TEST_APP_AUTHORED_MEMBERS\
    TEST_APP_WITH_TIMESTAMPS_MEMBERS\
    T_DIRECT_MEMBERS(TEST_APP_POST)
#define TEST_APP_POST_CONSTRUCTORS (TEST_APP_POST)


#define TEST_APP_COMMENT PG_TABLE_DEFINITION(\
    TEST_APP_COMMENT,\
    (test_app, comment),\
    (PG_COLUMN(PG_INT8, id))\
    (PG_COLUMN(PG_INT8, post_id)),\
    (TEST_APP_AUTHORED)(TEST_APP_WITH_TIMESTAMPS)\
)
#define TEST_APP_COMMENT_MEMBERS TEST_APP_AUTHORED_MEMBERS\
    TEST_APP_WITH_TIMESTAMPS_MEMBERS\
    T_DIRECT_MEMBERS(TEST_APP_COMMENT)
#define TEST_APP_COMMENT_CONSTRUCTORS (TEST_APP_COMMENT)


#define TEST_APP_COMMENT_POST PG_COMPOSITE_DEFINITION(\
    TEST_APP_COMMENT_POST,\
    (test_app, comment_post),\
    (PG_ATTRIBUTE(TEST_APP_COMMENT, comment))\
    (PG_ATTRIBUTE(TEST_APP_POST, post))\
    (PG_ATTRIBUTE(PG_TEXT, description))\
    (PG_ATTRIBUTE(TEST_APP_AUTHOR, author))\
)
#define TEST_APP_COMMENT_POST_MEMBERS T_DIRECT_MEMBERS(TEST_APP_COMMENT_POST)
#define TEST_APP_COMMENT_POST_CONSTRUCTORS (TEST_APP_COMMENT_POST)


#define TEST_APP_COMPOSITE_AUTHOR PG_COMPOSITE_DEFINITION(\
    TEST_APP_COMPOSITE_AUTHOR,\
    (test_app, composite_author),\
    (PG_ATTRIBUTE(PG_INT8, id))\
    (PG_ATTRIBUTE(PG_TEXT, biography))\
    (PG_ATTRIBUTE(PG_TEXT, name))\
)
#define TEST_APP_COMPOSITE_AUTHOR_MEMBERS T_DIRECT_MEMBERS(TEST_APP_COMPOSITE_AUTHOR)
#define TEST_APP_COMPOSITE_AUTHOR_CONSTRUCTORS (TEST_APP_COMPOSITE_AUTHOR)


/*#define TEST_APP_DOMAIN ALIAS_DEFINITION(\
    TEST_APP_DOMAIN,\
    (test_app, domain),\
    BTP_INT8\
)
#define TEST_APP_DOMAIN_CONSTRUCTORS (TEST_APP_DOMAIN) BTP_INT8_CONSTRUCTORS
#define TEST_APP_DOMAIN_INHERITANCE_CHAIN BTP_INT8_INHERITANCE_CHAIN (TEST_APP_DOMAIN)*/


#endif
